// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGRODTjhI_Mmu-Qdmnrk1stcqaPhOE-vE',
    appId: '1:408529345254:web:c5f64982e4f4aa887f3927',
    messagingSenderId: '408529345254',
    projectId: 're-note-cbeb0',
    authDomain: 're-note-cbeb0.firebaseapp.com',
    storageBucket: 're-note-cbeb0.firebasestorage.app',
    measurementId: 'G-MK9XDCD8Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQBkHpHHfj-jP6q_sTxpEMU1BSt8ED6I',
    appId: '1:408529345254:android:c9a9f3d83dfddd137f3927',
    messagingSenderId: '408529345254',
    projectId: 're-note-cbeb0',
    storageBucket: 're-note-cbeb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7_IvSJF8fj079WqQTXjNxKbXi0jth6gI',
    appId: '1:408529345254:ios:5c66172ab02e7a907f3927',
    messagingSenderId: '408529345254',
    projectId: 're-note-cbeb0',
    storageBucket: 're-note-cbeb0.firebasestorage.app',
    iosBundleId: 'com.example.reNote',
  );
}
